FROM golang:1.16 AS build
ADD . /app/src
WORKDIR /app/src
RUN make

FROM ubuntu
LABEL description="csif-driver plugin"
RUN apt-get update && apt-get install -y tgt open-iscsi && \
apt-get autoclean -y && apt-get autoremove -y && rm -rf /var/lib/apt-get/lists/*
COPY --from=build /app/src/bin/csif-plugin /csif-plugin
ENTRYPOINT ["/csif-plugin"]