FROM golang:1.16 AS build
ADD . /app/src
WORKDIR /app/src
RUN make filter

FROM ubuntu
LABEL description="csif-filter server"
RUN apt-get update && apt-get install -y tgt && \
apt-get autoclean -y && apt-get autoremove -y && rm -rf /var/lib/apt-get/lists/*
COPY --from=build /app/src/bin/csif-filter /csif-filter
ENTRYPOINT ["/csif-filter"]
