apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-iscsi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
  volumeName: pv-iscsi
  storageClassName: ""
