// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.3
// source: filter/filter.proto

package filter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterDeviceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tp   string `protobuf:"bytes,1,opt,name=tp,proto3" json:"tp,omitempty"`
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Iqn  string `protobuf:"bytes,3,opt,name=iqn,proto3" json:"iqn,omitempty"`
}

func (x *FilterDeviceInfo) Reset() {
	*x = FilterDeviceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filter_filter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterDeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterDeviceInfo) ProtoMessage() {}

func (x *FilterDeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_filter_filter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterDeviceInfo.ProtoReflect.Descriptor instead.
func (*FilterDeviceInfo) Descriptor() ([]byte, []int) {
	return file_filter_filter_proto_rawDescGZIP(), []int{0}
}

func (x *FilterDeviceInfo) GetTp() string {
	if x != nil {
		return x.Tp
	}
	return ""
}

func (x *FilterDeviceInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *FilterDeviceInfo) GetIqn() string {
	if x != nil {
		return x.Iqn
	}
	return ""
}

type CreateFilterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientDev *FilterDeviceInfo `protobuf:"bytes,1,opt,name=client_dev,json=clientDev,proto3" json:"client_dev,omitempty"`
}

func (x *CreateFilterRequest) Reset() {
	*x = CreateFilterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filter_filter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFilterRequest) ProtoMessage() {}

func (x *CreateFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filter_filter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFilterRequest.ProtoReflect.Descriptor instead.
func (*CreateFilterRequest) Descriptor() ([]byte, []int) {
	return file_filter_filter_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFilterRequest) GetClientDev() *FilterDeviceInfo {
	if x != nil {
		return x.ClientDev
	}
	return nil
}

type CreateFilterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerDev *FilterDeviceInfo `protobuf:"bytes,1,opt,name=server_dev,json=serverDev,proto3" json:"server_dev,omitempty"`
}

func (x *CreateFilterResponse) Reset() {
	*x = CreateFilterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filter_filter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFilterResponse) ProtoMessage() {}

func (x *CreateFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filter_filter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFilterResponse.ProtoReflect.Descriptor instead.
func (*CreateFilterResponse) Descriptor() ([]byte, []int) {
	return file_filter_filter_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFilterResponse) GetServerDev() *FilterDeviceInfo {
	if x != nil {
		return x.ServerDev
	}
	return nil
}

type DeleteFilterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientDev *FilterDeviceInfo `protobuf:"bytes,1,opt,name=client_dev,json=clientDev,proto3" json:"client_dev,omitempty"`
}

func (x *DeleteFilterRequest) Reset() {
	*x = DeleteFilterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filter_filter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFilterRequest) ProtoMessage() {}

func (x *DeleteFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_filter_filter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFilterRequest.ProtoReflect.Descriptor instead.
func (*DeleteFilterRequest) Descriptor() ([]byte, []int) {
	return file_filter_filter_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteFilterRequest) GetClientDev() *FilterDeviceInfo {
	if x != nil {
		return x.ClientDev
	}
	return nil
}

type DeleteFilterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteFilterResponse) Reset() {
	*x = DeleteFilterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_filter_filter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFilterResponse) ProtoMessage() {}

func (x *DeleteFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_filter_filter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFilterResponse.ProtoReflect.Descriptor instead.
func (*DeleteFilterResponse) Descriptor() ([]byte, []int) {
	return file_filter_filter_proto_rawDescGZIP(), []int{4}
}

var File_filter_filter_proto protoreflect.FileDescriptor

var file_filter_filter_proto_rawDesc = []byte{
	0x0a, 0x13, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x10, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x69, 0x71, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x71, 0x6e, 0x22,
	0x47, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x64, 0x65, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x76, 0x22, 0x48, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x30, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x76, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x44,
	0x65, 0x76, 0x22, 0x47, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x0a, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x5f, 0x64, 0x65, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x65, 0x76, 0x22, 0x16, 0x0a, 0x14, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x32, 0x86, 0x01, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x3d,
	0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x14,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a,
	0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x14, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x26, 0x5a, 0x24,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6f, 0x6f, 0x68, 0x36,
	0x34, 0x2f, 0x63, 0x73, 0x69, 0x66, 0x2d, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x2f, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_filter_filter_proto_rawDescOnce sync.Once
	file_filter_filter_proto_rawDescData = file_filter_filter_proto_rawDesc
)

func file_filter_filter_proto_rawDescGZIP() []byte {
	file_filter_filter_proto_rawDescOnce.Do(func() {
		file_filter_filter_proto_rawDescData = protoimpl.X.CompressGZIP(file_filter_filter_proto_rawDescData)
	})
	return file_filter_filter_proto_rawDescData
}

var file_filter_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_filter_filter_proto_goTypes = []interface{}{
	(*FilterDeviceInfo)(nil),     // 0: FilterDeviceInfo
	(*CreateFilterRequest)(nil),  // 1: CreateFilterRequest
	(*CreateFilterResponse)(nil), // 2: CreateFilterResponse
	(*DeleteFilterRequest)(nil),  // 3: DeleteFilterRequest
	(*DeleteFilterResponse)(nil), // 4: DeleteFilterResponse
}
var file_filter_filter_proto_depIdxs = []int32{
	0, // 0: CreateFilterRequest.client_dev:type_name -> FilterDeviceInfo
	0, // 1: CreateFilterResponse.server_dev:type_name -> FilterDeviceInfo
	0, // 2: DeleteFilterRequest.client_dev:type_name -> FilterDeviceInfo
	1, // 3: Filter.CreateFilter:input_type -> CreateFilterRequest
	3, // 4: Filter.DeleteFilter:input_type -> DeleteFilterRequest
	2, // 5: Filter.CreateFilter:output_type -> CreateFilterResponse
	4, // 6: Filter.DeleteFilter:output_type -> DeleteFilterResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_filter_filter_proto_init() }
func file_filter_filter_proto_init() {
	if File_filter_filter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_filter_filter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterDeviceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filter_filter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFilterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filter_filter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateFilterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filter_filter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFilterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_filter_filter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteFilterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_filter_filter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_filter_filter_proto_goTypes,
		DependencyIndexes: file_filter_filter_proto_depIdxs,
		MessageInfos:      file_filter_filter_proto_msgTypes,
	}.Build()
	File_filter_filter_proto = out.File
	file_filter_filter_proto_rawDesc = nil
	file_filter_filter_proto_goTypes = nil
	file_filter_filter_proto_depIdxs = nil
}
