apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostimg-static
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
  volumeName: pv-hostimg-static
  storageClassName: ""