apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostimg-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Mi
  storageClassName: csi-csif-hostimg-sc