kind: Pod
apiVersion: v1
metadata:
  name: pod-csi
spec:
  containers:
    - name: pod-csi-container
      image: busybox
      volumeMounts:
      - mountPath: "/volmount"
        name: volmount
      command: [ "sleep", "3000" ]
  volumes:
    - name: volmount
      persistentVolumeClaim:
        claimName: pvc-csi